schema_version = "1.0.0"
id = "persiantype"
name = "Persian type"
version = "2.0.1"
tagline = "Add Persian/Arabic type directly to Blender"
maintainer = "DAMYAR <farsayyad@gmail.com>"
blender_version_min = "5.0.1"
license = ["SPDX:GPL-3.0-or-later"]
type = "add-on"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",

]
